name: Flask App CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Debug: Check if Railway CLI URL is responding correctly
      - name: Debug Railway CLI URL
        run: |
          echo "Checking if Railway CLI URL is responding correctly"
          curl -I https://railway.app/cli/install.sh  # Get response headers

      # Install Railway CLI
      - name: Install Railway CLI
        run: |
          echo "Attempting to download Railway CLI installation script"
          curl -sSL https://railway.app/cli/install.sh -o railway_install.sh || exit 1
          echo "11111"
          bash railway_install.sh
          echo "22222"
          sudo mv railway /usr/local/bin
          echo "33333"

      # Login to Railway
      - name: Login to Railway
        run: |
          echo ${{ secrets.RAILWAY_API_KEY }} | railway login --apiKey

      # Deploy the Flask app to Railway
      - name: Deploy to Railway
        run: |
          railway up --service flask-app
        env:
          RAILWAY_API_KEY: ${{ secrets.RAILWAY_API_KEY }}
