name: Flask App CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Debug: Check if Railway CLI URL is responding correctly
      - name: Debug Railway CLI URL
        run: |
          echo "Checking if Railway CLI URL is responding correctly"
          curl -I https://railway.app/cli/install.sh  # Get response headers

      # Install Railway CLI using the recommended method from Railway docs
      - name: Install Railway CLI
        run: |
          echo "Attempting to download and install Railway CLI"
          bash <(curl -fsSL cli.new)
          if [ $? -ne 0 ]; then
            echo "Error installing Railway CLI"
            exit 1
          fi
          echo "Railway CLI installed successfully."

      # Set up Railway authentication token (use RAILWAY_API_KEY for project-level access)
      - name: Set Railway authentication token
        run: |
          echo "Setting up Railway authentication"
          echo "RAILWAY_API_KEY HERE : ${{ secrets.RAILWAY_API_KEY }}"
        env:
          RAILWAY_API_KEY: ${{ secrets.RAILWAY_API_KEY }} # Make sure the secret is named correctly

      # Deploy the Flask app to Railway
      - name: Deploy to Railway
        run: |
          echo "Deploying Flask app to Railway"
          railway up --service flask-app > railway_deploy_output.log 2>&1
          if [ $? -ne 0 ]; then
            echo "ERROR: Deployment failed. See the logs below:"
            cat railway_deploy_output.log
            exit 1
          fi
        env:
          RAILWAY_API_KEY: ${{ secrets.RAILWAY_API_KEY }} # Pass the secret as an environment variable

      # Example: Call Railway GraphQL API to fetch deployment status
      - name: Query Railway GraphQL API
        run: |
          echo "Querying Railway GraphQL API for deployment status"
          curl --request POST \
            --url https://backboard.railway.com/graphql/v2 \
            --header "Authorization: Bearer ${{ secrets.RAILWAY_API_KEY }}" \
            --header "Content-Type: application/json" \
            --data '{"query":"query { me { name email } }"}' > api_response.json

          # Optional: Print API response to check if it worked
          cat api_response.json

        env:
          RAILWAY_API_KEY: ${{ secrets.RAILWAY_API_KEY }} # Pass the secret to the API call

