name: Flask App CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH (if needed for deployment)
      - name: Set up SSH keys
        run: |
          echo "Setting up SSH keys..."

           # Create the .ssh directory
           mkdir -p ~/.ssh

           # Write the SSH private key to the id_rsa file
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

           # Set permissions for the SSH private key file
           chmod 600 ~/.ssh/id_rsa

           echo "11111..."
           # Start the SSH agent and add the key
           eval $(ssh-agent -s)
           ssh-add ~/.ssh/id_rsa

           # Check if the file was written correctly (without exposing the private key)
           ls -la ~/.ssh
           cat ~/.ssh/id_rsa | head -n 10  # Output first 10 lines (just for validation, not printing entire key)

           echo "222222..."

           # Add Render's server to the known hosts
           ssh-keyscan render.com >> ~/.ssh/known_hosts
           echo "333333..."
           # Ensure that the SSH key is configured correctly and test the SSH connection
           ssh -T git@render.com

      # Deploy to Render using Render CLI
      - name: Deploy to Render
        run: |
          # Install Render CLI
          curl -fsSL https://render.com/install.sh | bash

          # Deploy using Render CLI
          render deploy --service flask-app --branch main
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
